ARG ELASTIC_STACK_VERSION
FROM docker.elastic.co/elasticsearch/elasticsearch$distribution_suffix:$ELASTIC_STACK_VERSION

ARG plugin_path=/usr/share/plugins/plugin
ARG es_path=/usr/share/elasticsearch
ARG es_yml=$es_path/config/elasticsearch.yml

RUN rm -f $es_path/config/scripts

COPY --chown=elasticsearch:elasticsearch .ci/elasticsearch-run.sh $es_path/
