ARG ELASTIC_STACK_VERSION
FROM docker.elastic.co/elasticsearch/elasticsearch$distribution_suffix:$ELASTIC_STACK_VERSION

ARG es_path=/usr/share/elasticsearch
ARG es_yml=$es_path/config/elasticsearch.yml

RUN rm -f $es_path/config/scripts
