version: '3'

services:

  logstash:
    command: /usr/share/plugins/plugin/.ci/logstash-run.sh
    environment:
        - INTEGRATION=${INTEGRATION:-false}
        - SECURE_INTEGRATION=${SECURE_INTEGRATION:-false}
        - ELASTIC_STACK_VERSION=$ELASTIC_STACK_VERSION
        - ELASTIC_SECURITY_ENABLED=$ELASTIC_SECURITY_ENABLED
        - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
  elasticsearch:
    build:
      context: ../
      dockerfile: .ci/Dockerfile.elasticsearch
      args:
        - ELASTIC_STACK_VERSION=$ELASTIC_STACK_VERSION
        - INTEGRATION=${INTEGRATION:-false}
        - SECURE_INTEGRATION=${SECURE_INTEGRATION:-false}
    environment:
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - xpack.security.enabled=${ELASTIC_SECURITY_ENABLED:-false}
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms250m -Xmx800m
    tty: true
    ports:
      - "9200:9200"
    user: elasticsearch

